// Copyright 2024 Mikael Persson - Modernized to C++20
#ifndef BAGL_BAGL_DETAIL_INCLUDE_IMCOMPLETE_RANGES_H_
#define BAGL_BAGL_DETAIL_INCLUDE_IMCOMPLETE_RANGES_H_

#undef _LIBCPP_HAS_NO_INCOMPLETE_RANGES

#include <ranges>

#endif  // BAGL_BAGL_DETAIL_INCLUDE_IMCOMPLETE_RANGES_H_
